# Network & Performance Configuration
server.port=8080
gmc.websocket.sendbuffersizelimit=5120000
prometheus.scrape.interval=2s

# Management Console UI/Security Controls
gmc.tabs.gfsh.enabled=true
gmc.ssl-hostname-verification-enabled=true

# Authentication Configuration (Developer Mode Default)
gmc.security.mode=NONE